import time
# 30 valid cases for data types --> int, float, string, bool, complex
#----------------------------------integer------------------------------------
print("----------------------------------int data type----------------------------------")
print("test case 1")
x1 = 342
x2 = 125
sum = x1 + x2
print("the sum is : ",sum)
print(type(sum))
print()
print("test case 2")
print("multiplication : ",x1*x2)
print()
print("test case 3")
i1 = int(input("Enter an interger :"))
i2 = int(input("Enter another interger :"))
print("the difference :", i1-i2)
print()
print("test case 4")
print("the id of i1 is :",id(i1))
print("the id of i2 is :",id(i2))
print("test case 5")
x3 = 14000
print("x3 : ", x3)
print(type(x3))
print()
print("test case 6")
x4 = 100765
print("before division ",x4)
x4 = x4/i2
print("after division",x4)
print()
#----------------------------------float------------------------------------
print("--------------------------------------float data types--------------------------------------")
print("test case 1")
f1 = 124.9
f2 = 123.9
print("f1, f2:",f1,f2)
print("sum: ",f1+f2)
print("test case 2")
print("difference: ",f1-f2)
print(type(f1), type(f2))
print("test case 3")
f3 = float(input("enter float value 1: "))
f4 = float(input("enter a float value 2:"))
print("the values are :",f3,f4)
print("test case 4")
f5 = 3.e12
print(type(f5))
print("f5: ",f5)
print('id of f5 is: ',id(f5))
print("test case 5")
print("multiplication: ",f1*f2*f3*f4)
print()
print("test case 6")
print("divison of f5: ", f5/(f1+f2))
#----------------------------------string------------------------------------
print("----------------------------------------string data type---------------------------------------")
print("test case 1")
str1 = " this is a string"
print("string: ", str1)
print(type(str1))
print()
print("test case 2")
print("slicing in +ve direction: ",str1[2:7])
print()
print("test case 3")
print()
print("slicing in -ve direction: ",str1[-2:-10:-1])
print()
print("test case 4")
str2 = input("enter a string: ")
print("the string is :", str2)
print('the id is : ',id(str2))
print()
print("test case 5")
print("str2[0]: ", str2[0])
print()
print("test case 6")
print("string concatenation: ", str1 + str2)
print()
#----------------------------------boolean------------------------------------
print('----------------------------------------boolean data types----------------------------------------')
print('test case 1')
b1 = bool(input('input a value: '))
print('the value is: ',b1)
print(type(b1))
print("test case 2")
b2 = bool(input("enter another value: "))
print("sum of boolean:",b1+b2)
print("test case 3")
print("type and id of b1 is: ",end='')
print(type(b2))
print(id(b1))
print()
print("test case 4")
b3 = 1400
b3 = bool(False)
print("b3 :",b3)
print()
print("test case 5")
print("sum of 3 boolean values:", b1+b2+b3)
print()
print("test case 6")
print("false * anu mumber:", b3*10)
print()
#----------------------------------complex------------------------------------
print("----------------------------------------complex data types---------------------------------------")
print()
print("test case 1")
c1 = complex(input("enter 1st complex number: "))
c2 = complex(input("enter 2nd complex number: "))
print("the number are : ",c1, c2)
print()
print("test case 2")
print(" sum of complex numbers:",c1+c2)
print("difference of complex numbers : ",c1-c2)
print()
print("test case 3")
c3 = 92-93j
print("anothe complex number: ",c3)
print("real part of complex number is: ",c3.real)
print("imaginary part of complex number is: ",c3.imag)
print()
print('test case 4')
print('type: ',type(c3),'id:',id(c3))
print()
print('test case 5')
c4 = ord('A') + 88J
print(c4)
print()
print("test case 6")
print(c4+c3)
print()
time.sleep(2)
print("End of code")