#list data type with functions pop(),sort(),sorted()
l1 = [10,11,3,65,78,19,20] #[input("enter a list: ")]
print("The list entered is :", l1)
print("---------pop()--------")
print()
obj = l1.pop()
print("taking out last element: ",obj)
print()
obj2 = l1.pop(3)
print("taking out a specific index element in +ve direction: ",obj2)
obj3 = l1.pop(-2)
print("taking out a specific index element in -ve direction: ",obj3)
print()
print("============sort()=============")
l2 = [3,86,21,1,3,5]
print("extended list: ",l2)
print()
l1.extend(l2)
l1.sort()
print("The sorted list after pop : ", l1)
l1.sort(reverse=True)
r = l1.sort(reverse=True)
print(r)
print("descending order of the list: ",l1)
print()
x1 = sorted(l1)
print("using sorted()",x1)
x1 = sorted(l1,reverse=True)
print("reverse order: ",x1)
t1 = (1,2,6,4,2,7,9,112,4,2,1,3)
print("tuple t1 = ",t1)
ts1 = sorted(t1)
print("using sorted():",ts1)
ts1 = sorted(t1,reverse = True)
print("reverse order: ",ts1)
print()
td = {1:17,2:9,4:12,2:8,1:13}
tds1 = sorted(td)
print("sorting dictionary:",tds1)
td = {1:17,2:9,4:12,2:8,1:13}.keys()
tds1 = sorted(td)
print("sorting keys :",tds1)
td = {1:17,2:9,4:12,2:8,1:13}.values()
tds1 = sorted(td)
print("sorting values :",tds1)
td = {1:17,2:9,4:12,2:8,1:13}.items()
tds1 = sorted(td)
print("sorting items(keys and values) :",tds1)