#python code using predefined function for list data type
import time
#------------------------------------append()------------------------------------
print("================Using append()====================")
print("case 1")
l1 = [100, 'girish','hyd',0,'&']
course = 'python'
#input("Enter course name: ")
l1.append(course)
print(l1)
print()
print("case 2")
print("lenght of l1 before adding length: ",len(l1))
l1.append(len(l1))
print("after adding length to list: ",l1)
print()
print('case 3')
print("id: ",id(l1))
print("type: ",type(l1))
l1.append(id)
l1.append(type)
print(l1)
print()
print("case 4")
l2 = ['adding',2,'nd','list']
l1.append(l2)
print(l1)
print(l2)
print()
#------------------------------------remove()------------------------------------
print("=====================Using remove()====================")
print("case 1")
l1.remove(id)
l1.remove(type)
print(l1)
print()
print("case 2")
l1.append(0)
l1.remove(0)
print("Remove function works in forward direction")
print(l1)
print()
print('case 3')
l1.remove('girish')
l1.remove(l2)
print(l1)
print()
print('case 4')
for i in l1 :
    if i == 0:
        l1.remove(i)
print(l1)
print()
#------------------------------------extend()------------------------------------
print("==============Using extend()=================")
print('case 1')
l1.extend(l2)
l2.extend(l2)
print("after extending l2 with l2 and l1")
print(l1)
print(l2)
print()
print('case 2')
l1.clear()
l2.clear
l3 = list('matrix')
l1.extend(l3)
print('l1 = ',l1)
print()
print('case 3')
text = 'addition'
l2 = list(text)
l1.extend(l2)
print(l1)
print()
#------------------------------------copy()------------------------------------
print("=================Using copy()====================")
print('case 1')
x1 = l1.copy()
print(x1)
print()
print('case 2')
x2 = l2.copy()
print("length of x2: ",len(x2))
x2.extend(x1)
print(x2)
print()
print('case 3')
x2.clear()
x2 = x1.copy()
print(x2)
print()
#------------------------------------clear()------------------------------------
print("=================Using clear()====================")
print('case 1')
print("the x2 is : ",x2)
print(" after clear function: ",x2.clear())
print("none value is returned")
print()
print('case 2')
print("before clearing")
print("l1:",l1)
print('l2',l2)
print("after clearing")
l1.clear()
l2.clear()
print(l1,l2)
print()
print("case 3")
l1 = list('python')
l2 = list("core")
l3  = l2 + l1
print('new list l3',l3)
l3.clear()
print(l3)
print()
#------------------------------------insert()------------------------------------
print("=================Using insert()====================")
print('case 1')
l1.clear()
l2.clear()
l1.insert(0,10001)
l1.insert(1,10002)
print("new list l1 : ",l1)
print()
print('case 2')
print("Insert function in positive(+ve) direction ")
l2 = [chr(70),chr(71)]
l2.insert(0,chr(90))
l2.insert(1,'y')
l2.insert(2,'x')
print(l2)
print()
print('case 3')
print("Insert function in negative direction -n + -1th position")
l1.insert(-1,1003)
l1.insert(-1,1004)
print(l1)
print()
print("end of code")