s1 = {}
print(s1, type(s1))
s2 = set()
print(s2, type(s2))
print()
s3 = {12,13,14,15,16,chr(65)}
print("set does not support inseration: ",s3)
s4 = eval(input('enter a set values: '))
print()
print(s4, type(s4))
print()
print('The difference between set and tuple is that set is a dynamic and mutable data type')
print("=====Before adding elements=====")
print(s3)
print("=====After adding elements======")
s3.add('set')
s3.add('word2')
s3.remove(12)
print(s3)
print('but set data type does not support indexing and slicing which is supported by tuple data type')
print()
t1 = 12,34,89,90,98,89,'hello','max',129.09,100+90j
print('The tuple is: ',t1)
print("indexing and slicing the tuple")
print(t1[0:5])
print(t1[::-1])
print(t1[2])
print(t1[-2])
print(t1[-3:-7:-1])
for i in t1:
    print(i)
print()
print("where as when performing slicing or indexing on set data type results in error")
print(s3[0])
print(s3[0:2])
