#slice operator in forward(+ve direction)
import time
str1 = 'software engineer'
print('slice operator in  forward (+ve) direction')
print()
print(str1)
for i in range(len(str1)):
    print(str1[i],'=',i, end= " ")
print()
print()
print("test case 1 ")
print(str1[0:])
print()
print("test case 2 ")
print(str1[0:5])
print()
print("test case 3 ")
print(str1[:9])
print()
print("test case 4 ")
print(str1[:])
print()
print("test case 5 ")
print(str1[::])
print()
print("test case 6 ")
print(str1[1:15:3])
print()
print("test case 7 ")
print(str1[3:16:4])
print()
print("test case 8 ")
print(str1[9:])
print()
print("test case 9 ")
print(str1[0:8])
print()
print("test case 10 ")
print(str1[0:16:2])
print()
print("test case 11 ")
print(str1[0:16:1])
print()
print("test case 12 ")
print(str1[2:13])
print()
print("test case 13 ")
print(str1[9:12:1])
print()
print("test case 14 ")
print(str1[10:17:2])
print()
print("test case 15 ")
print(str1[7:10:2])
print()
print("test case 16 ")
print(str1[14:16])
print()
time.sleep(2)
print("End of code")